fixed error[E0063]: missing field `contract_identifier` in initializer of `STXLockEventData` --> src/clarity_vm/special.rs:111:60 111 | ...                   STXEventType::STXLockEvent(STXLockEventData {